version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: krasnodarbars
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/krasnodarbars
    depends_on:
      - db

volumes:
  db_data: